Replaced with 2.1

diff --git a/packaging/debian/opensips.init b/packaging/debian/opensips.init
--- a/packaging/debian/opensips.init
+++ b/packaging/debian/opensips.init
@@ -2,8 +2,8 @@
 #
 ### BEGIN INIT INFO
 # Provides:          opensips
-# Required-Start:    $syslog $network $local_fs $time
-# Required-Stop:     $syslog $network $local_fs
+# Required-Start:    $syslog $network $local_fs $time $remote_fs
+# Required-Stop:     $syslog $network $local_fs $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Start the OpenSIPS SIP server
@@ -19,16 +19,22 @@ PATH=/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/sbin/opensips
 NAME=opensips
 DESC=opensips
+CFGFILE=/etc/opensips/opensips.cfg
+M4CFGFILE=/etc/opensips/opensips.m4
+M4ARCHIVEDIR=/etc/opensips/archive
 HOMEDIR=/var/run/opensips
 PIDFILE=$HOMEDIR/$NAME.pid
 DEFAULTS=/etc/default/opensips
 RUN_OPENSIPS=no
 
+
+[-e "/lib/lsb/init-functions" ] && . /lib/lsb/init-functions
+
 # Do not start opensips if fork=no is set in the config file
 # otherwise the boot process will just stop
 check_fork ()
 {
-    if grep -q "^[[:space:]]*fork[[:space:]]*=[[:space:]]*no.*" /etc/opensips/opensips.cfg; then
+    if grep -q "^[[:space:]]*fork[[:space:]]*=[[:space:]]*no.*" $CFGFILE; then
 	echo "Not starting $DESC: fork=no specified in config file; run /etc/init.d/opensips debug instead"
 	exit 1
     fi
@@ -38,7 +44,7 @@ check_opensips_config ()
 {
 	# Check if opensips configuration is valid before starting the server
 	set +e
-	out=$($DAEMON -c 2>&1 > /dev/null)
+	out=$($DAEMON -c -f $CFGFILE 2>&1 > /dev/null)
 	retcode=$?
 	set -e
 	if [ "$retcode" != '0' ]; then
@@ -103,7 +109,7 @@ if test "$DUMP_CORE" = "yes" ; then
     # echo "$COREDIR/core.%e.sig%s.%p" > /proc/sys/kernel/core_pattern
 fi
 
-OPTIONS="-P $PIDFILE -m $S_MEMORY -M $P_MEMORY -u $USER -g $GROUP"
+OPTIONS="-P $PIDFILE -m $S_MEMORY -M $P_MEMORY -u $USER -g $GROUP -f $CFGFILE"
 
 case "$1" in
   start|debug)
@@ -118,6 +124,28 @@ case "$1" in
 	mkdir -p "$HOMEDIR"
 	chmod 775 "$HOMEDIR"
 	chown "$USER:$GROUP" "$HOMEDIR" >/dev/null 2>&1 || true
+
+	# Generate config from M4
+	if [ -f $M4CFGFILE ]; then
+		m4 -Q $M4CFGFILE >$CFGFILE.tmp
+		if [ $? != 0 ]; then
+			echo "Cannot process m4 macro"
+			rm "$CFGFILE.tmp"
+			exit 1
+		fi
+
+		[ -e $CFGFILE ] || touch $CFGFILE
+
+		# compare configs
+		if [ `md5sum $CFGFILE|awk '{print $1}'` != `md5sum $CFGFILE.tmp|awk '{print $1}'` ]; then
+			mkdir -p "$M4ARCHIVEDIR"
+			mv "$CFGFILE" "$M4ARCHIVEDIR/$NAME.cfg-`date +%Y%m%d_%H%M%S`"
+		fi
+
+		mv "$CFGFILE.tmp" "$CFGFILE"
+		chown $USER:$GROUP $CFGFILE
+		chmod 640 $CFGFILE
+	fi
 
 	echo -n "Starting $DESC: $NAME"
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
